<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.M2nWCU6' shared service.

return $this->privates['.service_locator.M2nWCU6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\PageBuilderController::edit' => ['privates', '.service_locator.28hpvOx', 'get_ServiceLocator_28hpvOxService.php', true],
    'App\\Controller\\PageBuilderController:edit' => ['privates', '.service_locator.28hpvOx', 'get_ServiceLocator_28hpvOxService.php', true],
], [
    'App\\Controller\\PageBuilderController::edit' => '?',
    'App\\Controller\\PageBuilderController:edit' => '?',
]);
