<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.28hpvOx.phpDocumentor\Reflection\Types\Integer' shared service.

include_once $this->targetDirs[3].'/vendor/phpdocumentor/type-resolver/src/Type.php';
include_once $this->targetDirs[3].'/vendor/phpdocumentor/type-resolver/src/Types/Integer.php';

return $this->privates['.errored..service_locator.28hpvOx.phpDocumentor\\Reflection\\Types\\Integer'] = new \phpDocumentor\Reflection\Types\Integer();
