<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8N3ep6k\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8N3ep6k/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8N3ep6k.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8N3ep6k\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container8N3ep6k\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '8N3ep6k',
    'container.build_id' => '351f8570',
    'container.build_time' => 1576162011,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8N3ep6k');
