<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container68daMhS\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container68daMhS/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container68daMhS.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container68daMhS\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container68daMhS\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '68daMhS',
    'container.build_id' => '901c7c8f',
    'container.build_time' => 1578652820,
], __DIR__.\DIRECTORY_SEPARATOR.'Container68daMhS');
