<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW7oexXl\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW7oexXl/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW7oexXl.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW7oexXl\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerW7oexXl\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'W7oexXl',
    'container.build_id' => '517692ec',
    'container.build_time' => 1576070153,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW7oexXl');
